### ISSUE TITLE
以“游戏名+作者名”给文件夹命名，修改为：FlyBird-陈言必行。rest LGTM

### ISSUE THREAD

**Issue by Czhenya** [xitu/game-garden#11]
以“游戏名+作者名”给文件夹命名，修改为：FlyBird-陈言必行。rest LGTM

_Originally posted by @husiyu in https://github.com/xitu/game-garden/pull/9#pullrequestreview-927262077_

**Comment by Czhenya** [comment]
已修改

**Comment by siyu-hu** [comment]
已合并。
